In [4]:
import numpy as np

In [5]:
#ex1
one = np.arange(1, 11)
print(one)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#ex2
two = np.zeros((3,3))
print(two)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#ex3
three = np.random.randint(1, 11, size=(5,5))
print(three)

[[ 4  9  2  8  6]
 [ 5  5  7  1  5]
 [ 2  2  7  5  4]
 [ 5  3  9 10  3]
 [ 6  2  4  7  9]]


In [8]:
#ex4
four = np.random.rand(4,4)
print(four)

[[0.35608164 0.81308666 0.33004668 0.83570459]
 [0.67766267 0.09296619 0.12796271 0.31851915]
 [0.24899016 0.12308421 0.57491665 0.18163559]
 [0.15909508 0.40782651 0.35035208 0.17905639]]


In [15]:
#ex5
first_five = np.random.randint(1, 11, size=5)
second_five = np.random.randint(1, 11, size=5)

print("Перший масив:", first_five)
print("Другий масив:", second_five)

print("Сума масивів:", np.add(first_five, second_five))
print("Різниця масивів:", np.subtract(first_five, second_five))
print("Добуток масивів:", np.multiply(first_five, second_five))

Перший масив: [ 7 10  4  6 10]
Другий масив: [2 5 1 5 2]
Сума масивів: [ 9 15  5 11 12]
Різниця масивів: [5 5 3 1 8]
Добуток масивів: [14 50  4 30 20]


In [17]:
#ex6
first_veсtor = np.random.randint(1, 10, 7)
second_veсtor = np.random.randint(1, 10, 7)

print("Перший вектор:", first_veсtor)
print("Другий вектор:", second_veсtor)

dot = np.dot(first_veсtor, second_veсtor)

print("Скалярний добуток:", dot)

Перший вектор: [8 8 6 4 1 3 6]
Другий вектор: [1 7 5 2 7 9 1]
Скалярний добуток: 142


In [19]:
#ex7
first_matrix = np.random.randint(1, 10, size=(2, 2))
second_matrix = np.random.randint(1, 10, size=(2, 3))

print("Перша матриця:\n", first_matrix)
print("Друга матриця:\n", second_matrix)

dot_matrix = np.dot(first_matrix, second_matrix)

print("Результат множення матриць:\n", dot_matrix)

Перша матриця:
 [[1 9]
 [3 4]]
Друга матриця:
 [[2 8 3]
 [6 5 1]]
Результат множення матриць:
 [[56 53 12]
 [30 44 13]]


In [21]:
#ex8
matrix = np.random.randint(1, 10, size=(3, 3))

print("Початкова матриця:\n", matrix)

transposed_matrix = matrix.T

print("Транспонована матриця:\n", transposed_matrix)

Початкова матриця:
 [[7 2 2]
 [4 8 8]
 [5 7 4]]
Транспонована матриця:
 [[7 4 5]
 [2 8 7]
 [2 8 4]]


In [22]:
#ex9
matrix = np.random.rand(4, 4)

print("Початкова матриця:\n", matrix)

transposed_matrix = matrix.T

print("Транспонована матриця:\n", transposed_matrix)

Початкова матриця:
 [[0.46498175 0.70110227 0.90860339 0.02850839]
 [0.83463106 0.66877788 0.11741108 0.90923025]
 [0.35194906 0.43654151 0.58790603 0.20979628]
 [0.88852056 0.70777415 0.31954848 0.35548071]]
Транспонована матриця:
 [[0.46498175 0.83463106 0.35194906 0.88852056]
 [0.70110227 0.66877788 0.43654151 0.70777415]
 [0.90860339 0.11741108 0.58790603 0.31954848]
 [0.02850839 0.90923025 0.20979628 0.35548071]]


In [23]:
#ex10
matrix = np.random.randint(1, 10, size=(3, 4))
vector = np.random.randint(1, 10, size=4)
print("Матриця:\n", matrix)
print("\nВектор:\n", vector)

result = np.dot(matrix, vector)

print("\nРезультат множення матриці на вектор:\n", result)

Матриця:
 [[3 3 3 8]
 [5 7 5 9]
 [9 3 7 2]]

Вектор:
 [3 8 8 1]

Результат множення матриці на вектор:
 [ 65 120 109]


In [24]:
#ex11
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print("Матриця:\n", matrix)
print("\nВектор:\n", vector)

result = np.dot(matrix, vector)

print("\nРезультат множення матриці на вектор:\n", result)

Матриця:
 [[0.15227317 0.06744676 0.21121058]
 [0.76594038 0.18848333 0.76757262]]

Вектор:
 [0.69122708 0.48523901 0.91647383]

Результат множення матриці на вектор:
 [0.33155211 1.32435841]


In [25]:
#ex12
first_matrix = np.random.randint(1, 10, size=(2, 2))
second_matrix = np.random.randint(1, 10, size=(2, 2))

print("Перша матриця:\n", first_matrix)
print("\nДруга матриця:\n", second_matrix)

elementwise_product = np.multiply(first_matrix, second_matrix)

print("\nРезультат поелементного множення:\n", elementwise_product)

Перша матриця:
 [[1 7]
 [2 4]]

Друга матриця:
 [[2 1]
 [5 8]]

Результат поелементного множення:
 [[ 2  7]
 [10 32]]


In [26]:
#ex13
first_matrix = np.random.randint(1, 10, size=(2, 2))
second_matrix = np.random.randint(1, 10, size=(2, 2))

print("Перша матриця:\n", first_matrix)
print("\nДруга матриця:\n", second_matrix)

product_matrix = np.dot(first_matrix, second_matrix)

print("\nДобуток матриць:\n", product_matrix)

Перша матриця:
 [[4 8]
 [9 7]]

Друга матриця:
 [[8 6]
 [4 5]]

Добуток матриць:
 [[ 64  64]
 [100  89]]


In [27]:
#ex14
matrix = np.random.randint(1, 101, size=(5, 5))

print("Матриця:\n", matrix)

sum_of_elements = np.sum(matrix)

print("\nСума елементів матриці:", sum_of_elements)

Матриця:
 [[28 99 75 17 26]
 [45 92 85  4 61]
 [ 5 44  2 70 96]
 [55 73 43 76 87]
 [50 79 92 45 23]]

Сума елементів матриці: 1372


In [28]:
#ex15
first_matrix = np.random.randint(1, 11, size=(4, 4))
second_matrix = np.random.randint(1, 11, size=(4, 4))

print("Перша матриця:\n", first_matrix)
print("\nДруга матриця:\n", second_matrix)

difference_matrix = first_matrix - second_matrix

print("\nРізниця матриць:\n", difference_matrix)

Перша матриця:
 [[ 9  6 10  9]
 [ 7  6  7  5]
 [ 5  5  4  9]
 [ 8  2  1  1]]

Друга матриця:
 [[7 3 8 6]
 [7 2 8 1]
 [3 6 1 9]
 [6 4 3 1]]

Різниця матриць:
 [[ 2  3  2  3]
 [ 0  4 -1  4]
 [ 2 -1  3  0]
 [ 2 -2 -2  0]]


In [29]:
#ex16
matrix = np.random.rand(3, 3)

print("Матриця:\n", matrix)

sum_vector = np.sum(matrix, axis=1)
sum_vector_column = sum_vector.reshape(-1, 1)

print("\nВектор-стовпчик з сумами елементів кожного рядка матриці:\n", sum_vector_column)

Матриця:
 [[0.10077214 0.14388451 0.11548759]
 [0.50615334 0.88742198 0.95769182]
 [0.13687079 0.79683894 0.03754747]]

Вектор-стовпчик з сумами елементів кожного рядка матриці:
 [[0.36014424]
 [2.35126714]
 [0.97125719]]


In [30]:
#ex17
matrix = np.random.randint(1, 10, size=(3, 4))

print("Початкова матриця:\n", matrix)

squared_matrix = np.square(matrix)

print("\nМатриця з квадратами чисел:\n", squared_matrix)

Початкова матриця:
 [[9 8 2 5]
 [9 4 4 5]
 [4 8 3 7]]

Матриця з квадратами чисел:
 [[81 64  4 25]
 [81 16 16 25]
 [16 64  9 49]]


In [32]:
#ex18
vector = np.random.randint(1, 51, size=4)

print("Початковий вектор:\n", vector)

sqrt_vector = np.sqrt(vector)

print("\nВектор з квадратними коренями чисел:\n", sqrt_vector)

Початковий вектор:
 [46 17 13 39]

Вектор з квадратними коренями чисел:
 [6.78232998 4.12310563 3.60555128 6.244998  ]
